import {
  Profile,
  Post,
  Comment,
  UserExperience,
  Report,
  ModerationAction,
  VerificationRequest,
  AdminAuditLog,
  SystemSetting,
  Progress,
  Milestone,
  Proof,
} from '@/types/database';
import { AdminUser, AdminStaffItem } from '@/types/admin';

export const CURRENT_ADMIN: AdminUser = {
  id: 'usr-admin-01',
  email: 'admin@vera.id',
  full_name: 'Rezky Aditya (Operations)',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  role: 'SUPER_ADMIN',
  permissions: ['all'],
};

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'usr-001',
    username: 'andisaputra',
    full_name: 'Andi Saputra',
    email: 'andi.saputra@gmail.com',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    bio: 'Software engineer & tech enthusiast. Suka bantu orang milih gadget yang tepat.',
    decision_score: 92,
    reputation_tier: 'Top Penimbang',
    decisions_count: 142,
    experiences_count: 89,
    helpful_count: 1240,
    status: 'active',
    created_at: '2025-11-12T08:00:00Z',
    updated_at: '2026-09-01T12:00:00Z',
    last_active_at: '2026-09-07T14:20:00Z',
    roles: ['USER'],
  },
  {
    id: 'usr-002',
    username: 'budi_hartono',
    full_name: 'Budi Hartono',
    email: 'budi.h@outlook.com',
    avatar_url: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
    bio: 'Freelance graphic designer di Surabaya.',
    decision_score: 78,
    reputation_tier: 'Senior',
    decisions_count: 45,
    experiences_count: 22,
    helpful_count: 310,
    status: 'active',
    created_at: '2026-01-15T09:30:00Z',
    updated_at: '2026-09-06T11:00:00Z',
    last_active_at: '2026-09-07T10:15:00Z',
    roles: ['USER'],
  },
  {
    id: 'usr-003',
    username: 'cryptospam_bot',
    full_name: 'Crypto Gain Official',
    email: 'promo@quickmoney.cc',
    avatar_url: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=100&auto=format&fit=crop&q=80',
    bio: 'Klik link di bio untuk cuan harian 500%!',
    decision_score: 12,
    reputation_tier: 'Baru',
    decisions_count: 3,
    experiences_count: 0,
    helpful_count: 0,
    status: 'banned',
    ban_reason: 'Spam link phishing & bot penipuan massal pada Decision Room.',
    created_at: '2026-09-05T03:00:00Z',
    updated_at: '2026-09-06T15:20:00Z',
    last_active_at: '2026-09-06T15:20:00Z',
    roles: ['USER'],
  },
  {
    id: 'usr-004',
    username: 'dimas_toxic',
    full_name: 'Dimas Anggoro',
    email: 'dimas.anggoro99@gmail.com',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    bio: 'Gamer PC & audiofil.',
    decision_score: 44,
    reputation_tier: 'Member',
    decisions_count: 18,
    experiences_count: 8,
    helpful_count: 45,
    status: 'suspended',
    suspended_until: '2026-09-14T00:00:00Z',
    ban_reason: 'Pelecehan verbal berulang di kolom komentar produk.',
    created_at: '2026-03-20T14:10:00Z',
    updated_at: '2026-09-07T08:00:00Z',
    last_active_at: '2026-09-07T08:00:00Z',
    roles: ['USER'],
  },
  {
    id: 'usr-005',
    username: 'citra_ayu',
    full_name: 'Citra Kirana Ayu',
    email: 'citra.ayu@gmail.com',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    bio: 'Photographer & daily vlogger.',
    decision_score: 88,
    reputation_tier: 'Top Penimbang',
    decisions_count: 76,
    experiences_count: 48,
    helpful_count: 890,
    status: 'active',
    created_at: '2025-12-01T10:00:00Z',
    updated_at: '2026-09-07T12:00:00Z',
    last_active_at: '2026-09-07T13:45:00Z',
    roles: ['MODERATOR'],
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-001',
    author_id: 'usr-001',
    author: MOCK_PROFILES[0],
    title: 'Laptop 5–7 juta untuk coding & multitasking skripsi',
    category: 'Elektronik',
    description: 'Saya butuh laptop untuk coding web development (React/Node.js), sering dibawa kerja di luar, keyboard harus empuk, budget maks 7 juta.',
    min_budget: 5000000,
    max_budget: 7000000,
    priorities: ['Performa', 'Keyboard', 'Portabilitas', 'Durabilitas'],
    condition_preference: 'Tidak masalah',
    status: 'published',
    participants_count: 428,
    experiences_count: 86,
    answered_percentage: 73,
    top_candidate_name: 'ThinkPad X390',
    ai_risk_score: 4,
    created_at: '2026-09-02T10:00:00Z',
    updated_at: '2026-09-07T11:00:00Z',
  },
  {
    id: 'post-002',
    author_id: 'usr-002',
    author: MOCK_PROFILES[1],
    title: 'Monitor 27 inch 2K untuk color grading budget 3 jutaan',
    category: 'Elektronik',
    description: 'Cari monitor IPS sRGB > 99% untuk desain grafis dan editing video di kamar kecil.',
    min_budget: 2500000,
    max_budget: 3500000,
    priorities: ['Akurasi Warna', 'Resolusi', 'Garansi'],
    condition_preference: 'Baru',
    status: 'published',
    participants_count: 185,
    experiences_count: 34,
    answered_percentage: 68,
    top_candidate_name: 'LG 27QN600',
    ai_risk_score: 8,
    created_at: '2026-09-04T14:30:00Z',
    updated_at: '2026-09-07T09:15:00Z',
  },
  {
    id: 'post-003',
    author_id: 'usr-003',
    author: MOCK_PROFILES[2],
    title: 'Investasi Bot Cepat Kaya 100% Legal Profit Harian',
    category: 'Lainnya',
    description: 'Gabung channel telegram t.me/cuanjutawan sekarang juga sebelum kuota habis!',
    min_budget: 100000,
    max_budget: 50000000,
    priorities: ['Untung Cepat'],
    condition_preference: 'Baru',
    status: 'removed',
    participants_count: 12,
    experiences_count: 0,
    answered_percentage: 0,
    top_candidate_name: 'None',
    ai_risk_score: 98,
    removal_reason: 'Terbukti skema penipuan & spam referral telegram.',
    removed_by: 'usr-admin-01',
    removed_at: '2026-09-06T15:22:00Z',
    created_at: '2026-09-06T15:00:00Z',
    updated_at: '2026-09-06T15:22:00Z',
  },
  {
    id: 'post-004',
    author_id: 'usr-004',
    author: MOCK_PROFILES[3],
    title: 'Semua laptop brand lokal sampah gak layak beli',
    category: 'Elektronik',
    description: 'Jangan pernah beli brand A dan B, semuanya penipu dan teknisinya bodoh.',
    min_budget: 3000000,
    max_budget: 6000000,
    priorities: ['Anti Rusak'],
    condition_preference: 'Baru',
    status: 'hidden',
    participants_count: 54,
    experiences_count: 3,
    answered_percentage: 10,
    top_candidate_name: 'None',
    ai_risk_score: 84,
    removal_reason: 'Ujaran kebencian & pencemaran nama baik tanpa bukti objektif.',
    removed_by: 'usr-admin-01',
    removed_at: '2026-09-07T08:10:00Z',
    created_at: '2026-09-07T07:30:00Z',
    updated_at: '2026-09-07T08:10:00Z',
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'comm-001',
    post_id: 'post-001',
    post_title: 'Laptop 5–7 juta untuk coding & multitasking skripsi',
    author_id: 'usr-001',
    author: MOCK_PROFILES[0],
    content: 'Keyboard ThinkPad X390 memang gak ada lawan di harga segini. Trackpoint-nya sangat bantu pas lagi ngetik cepet.',
    usage_duration: '8 bulan pemakaian',
    sentiment: 'positif',
    verified_owner: true,
    likes_count: 34,
    status: 'published',
    created_at: '2026-09-03T11:00:00Z',
  },
  {
    id: 'comm-002',
    post_id: 'post-001',
    post_title: 'Laptop 5–7 juta untuk coding & multitasking skripsi',
    author_id: 'usr-004',
    author: MOCK_PROFILES[3],
    content: 'Lu yang beli laptop bekas ThinkPad emang miskin aja, beli dong MacBook M3 Pro kayak gua goblok.',
    usage_duration: 'Tidak pernah pakai',
    sentiment: 'negatif',
    verified_owner: false,
    likes_count: 0,
    status: 'hidden',
    removal_reason: 'Pelecehan verbal & pelanggaran etika komunitas.',
    created_at: '2026-09-07T07:45:00Z',
  },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: 'rep-8921',
    reporter_id: 'usr-002',
    reporter: MOCK_PROFILES[1],
    target_type: 'post',
    target_id: 'post-003',
    target_preview: 'Investasi Bot Cepat Kaya 100% Legal Profit Harian...',
    reason: 'scam',
    details: 'User mempromosikan bot judi online dan phishing wallet di dalam Decision Room.',
    priority: 'critical',
    status: 'resolved',
    assigned_to: 'usr-admin-01',
    assigned_moderator: MOCK_PROFILES[4],
    resolution_notes: 'Postingan dihapus dan akun pelaku dibanned permanen.',
    resolved_at: '2026-09-06T15:22:00Z',
    created_at: '2026-09-06T15:10:00Z',
  },
  {
    id: 'rep-8922',
    reporter_id: 'usr-001',
    reporter: MOCK_PROFILES[0],
    target_type: 'comment',
    target_id: 'comm-002',
    target_preview: 'Lu yang beli laptop bekas ThinkPad emang miskin...',
    reason: 'harassment',
    details: 'Menghina anggota komunitas secara kasar tanpa konteks produktif.',
    priority: 'high',
    status: 'pending',
    assigned_to: null,
    created_at: '2026-09-07T08:00:00Z',
  },
  {
    id: 'rep-8923',
    reporter_id: 'usr-005',
    reporter: MOCK_PROFILES[4],
    target_type: 'post',
    target_id: 'post-004',
    target_preview: 'Semua laptop brand lokal sampah gak layak beli...',
    reason: 'hate',
    details: 'Tuduhan sepihak tanpa menyertakan bukti invoice atau pengalaman riil.',
    priority: 'medium',
    status: 'reviewing',
    assigned_to: 'usr-admin-01',
    assigned_moderator: MOCK_PROFILES[4],
    created_at: '2026-09-07T08:15:00Z',
  },
  {
    id: 'rep-8924',
    reporter_id: 'usr-002',
    reporter: MOCK_PROFILES[1],
    target_type: 'user',
    target_id: 'usr-003',
    target_preview: 'Akun Crypto Gain Official',
    reason: 'impersonation',
    details: 'Mengaku sebagai affiliate resmi VERA untuk menarik dana pengguna.',
    priority: 'critical',
    status: 'resolved',
    assigned_to: 'usr-admin-01',
    resolution_notes: 'Tindakan ban permanen diterapkan.',
    resolved_at: '2026-09-06T15:25:00Z',
    created_at: '2026-09-06T15:15:00Z',
  },
];

export const MOCK_VERIFICATIONS: VerificationRequest[] = [
  {
    id: 'ver-101',
    user_id: 'usr-001',
    user: MOCK_PROFILES[0],
    verification_type: 'purchase_invoice',
    title: 'Bukti Pembelian Lenovo ThinkPad X390',
    submitted_info: {
      merchant: 'Tokopedia Official Store',
      invoice_number: 'INV/20251210/MPL/3920192',
      purchase_date: '10 Desember 2025',
      purchase_price: 'Rp 5.750.000',
    },
    document_urls: [
      'https://images.unsplash.com/photo-1554415707-9e4966a604f7?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'approved',
    reviewer_id: 'usr-admin-01',
    reviewer: MOCK_PROFILES[4],
    reviewer_notes: 'Invoice terverifikasi resmi dan foto fisik unit cocok dengan nomor seri.',
    submitted_at: '2026-09-01T09:00:00Z',
    reviewed_at: '2026-09-01T11:30:00Z',
  },
  {
    id: 'ver-102',
    user_id: 'usr-002',
    user: MOCK_PROFILES[1],
    verification_type: 'purchase_invoice',
    title: 'Bukti Pembelian Monitor LG 27QN600',
    submitted_info: {
      merchant: 'Bhinneka Store',
      invoice_number: 'INV-BHN-882910',
      purchase_date: '20 Januari 2026',
      purchase_price: 'Rp 3.100.000',
    },
    document_urls: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'pending',
    submitted_at: '2026-09-07T08:00:00Z',
  },
];

export const MOCK_EXPERIENCES: UserExperience[] = [
  {
    id: 'exp-001',
    post_id: 'post-001',
    author_id: 'usr-001',
    author: MOCK_PROFILES[0],
    product_name: 'ThinkPad X390 (Intel Core i5-8365U, 16GB RAM)',
    usage_duration: '8 bulan pemakaian',
    outcome_status: '100% Sesuai Ekspektasi',
    ratings: {
      coding: 5.0,
      gaming: 3.0,
      battery: 4.0,
      buildQuality: 5.0,
      valueForMoney: 4.8,
    },
    review_text: 'Setelah 8 bulan pemakaian untuk coding Node.js & Docker sehari-hari, laptop ini sangat memuaskan. Keyboard ThinkPad sangat mengurangi pegal tangan. Baterai tahan 4-5 jam kerja intensif.',
    proof_photos: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&auto=format&fit=crop&q=80',
    ],
    invoice_url: 'https://images.unsplash.com/photo-1554415707-9e4966a604f7?w=600&auto=format&fit=crop&q=80',
    verification_status: 'approved',
    verified_by: 'usr-admin-01',
    verified_at: '2026-09-01T11:30:00Z',
    likes_count: 86,
    status: 'published',
    created_at: '2026-09-01T09:00:00Z',
  },
];

export const MOCK_AUDIT_LOGS: AdminAuditLog[] = [
  {
    id: 'aud-9901',
    admin_id: 'usr-admin-01',
    admin_email: 'admin@vera.id',
    action: 'USER_BANNED',
    target_type: 'user',
    target_id: 'usr-003',
    ip_address: '103.144.12.8',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) VERA Control Center',
    metadata: { reason: 'Spam link phishing massal', duration: 'permanent' },
    created_at: '2026-09-06T15:22:00Z',
  },
  {
    id: 'aud-9902',
    admin_id: 'usr-admin-01',
    admin_email: 'admin@vera.id',
    action: 'POST_REMOVED',
    target_type: 'post',
    target_id: 'post-003',
    ip_address: '103.144.12.8',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) VERA Control Center',
    metadata: { reason: 'Skema penipuan & spam telegram', post_title: 'Investasi Bot Cepat Kaya' },
    created_at: '2026-09-06T15:20:00Z',
  },
  {
    id: 'aud-9903',
    admin_id: 'usr-admin-01',
    admin_email: 'admin@vera.id',
    action: 'VERIFICATION_APPROVED',
    target_type: 'verification',
    target_id: 'ver-101',
    ip_address: '103.144.12.8',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) VERA Control Center',
    metadata: { user: 'andisaputra', product: 'ThinkPad X390' },
    created_at: '2026-09-01T11:30:00Z',
  },
  {
    id: 'aud-9904',
    admin_id: 'usr-admin-01',
    admin_email: 'admin@vera.id',
    action: 'USER_SUSPENDED',
    target_type: 'user',
    target_id: 'usr-004',
    ip_address: '103.144.12.8',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) VERA Control Center',
    metadata: { duration_hours: 168, reason: 'Pelecehan verbal berulang di komentar' },
    created_at: '2026-09-07T08:00:00Z',
  },
];

export const MOCK_ADMINS: AdminStaffItem[] = [
  {
    id: 'adm-01',
    name: 'Rezky Aditya',
    email: 'admin@vera.id',
    role: 'SUPER_ADMIN' as const,
    status: 'active',
    last_active: '2026-09-07T14:30:00Z',
    created_at: '2025-10-01T00:00:00Z',
  },
  {
    id: 'adm-02',
    name: 'Citra Kirana',
    email: 'citra.mod@vera.id',
    role: 'MODERATOR' as const,
    status: 'active',
    last_active: '2026-09-07T12:00:00Z',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'adm-03',
    name: 'Rian Pratama',
    email: 'rian.admin@vera.id',
    role: 'ADMIN' as const,
    status: 'active',
    last_active: '2026-09-06T18:00:00Z',
    created_at: '2026-02-15T00:00:00Z',
  },
];

export const MOCK_SETTINGS: SystemSetting[] = [
  {
    key: 'platform_name',
    value: 'VERA Social Platform',
    description: 'Nama platform resmi yang ditampilkan di publik',
    updated_at: '2026-09-01T00:00:00Z',
  },
  {
    key: 'registration_enabled',
    value: true,
    description: 'Izinkan pendaftaran akun baru',
    updated_at: '2026-09-01T00:00:00Z',
  },
  {
    key: 'auto_moderation_threshold',
    value: 85,
    description: 'Skor risiko otomatis untuk menandai konten (0 - 100)',
    updated_at: '2026-09-01T00:00:00Z',
  },
  {
    key: 'max_upload_size_mb',
    value: 10,
    description: 'Batas ukuran file bukti verifikasi dalam MB',
    updated_at: '2026-09-01T00:00:00Z',
  },
  {
    key: 'maintenance_mode',
    value: false,
    description: 'Kunci platform hanya untuk staf administrator',
    updated_at: '2026-09-01T00:00:00Z',
  },
];

export const MOCK_PROGRESSES: Progress[] = [
  {
    id: 'prog-001',
    user_id: 'usr-001',
    user: MOCK_PROFILES[0],
    title: 'Membangun VERA Social Progress Platform',
    description: 'Mengembangkan aplikasi mobile React Native + Expo dan web Control Center Next.js dari awal hingga production.',
    category: 'Coding',
    start_date: '2026-08-01',
    end_date: null,
    status: 'active',
    visibility: 'public',
    cover_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    milestones_count: 5,
    proofs_count: 3,
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-09-07T18:00:00Z',
  },
  {
    id: 'prog-002',
    user_id: 'usr-002',
    user: MOCK_PROFILES[1],
    title: 'Belajar UI/UX Design & Design System',
    description: 'Belajar Figma, token warna, typography, dan micro-animations untuk aplikasi mobile.',
    category: 'Design',
    start_date: '2026-07-15',
    end_date: '2026-08-30',
    status: 'completed',
    visibility: 'public',
    cover_url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600&auto=format&fit=crop&q=80',
    milestones_count: 4,
    proofs_count: 2,
    created_at: '2026-07-15T09:00:00Z',
    updated_at: '2026-08-30T17:00:00Z',
  },
  {
    id: 'prog-003',
    user_id: 'usr-003',
    user: MOCK_PROFILES[2],
    title: 'Cuan Crypto Kilat 500% Sehari',
    description: 'Gabung channel telegram VIP untuk sinyal trading instan kaya.',
    category: 'Business',
    start_date: '2026-09-05',
    end_date: null,
    status: 'active',
    visibility: 'public',
    milestones_count: 1,
    proofs_count: 1,
    created_at: '2026-09-05T04:00:00Z',
    updated_at: '2026-09-05T04:00:00Z',
  },
];

export const MOCK_PROOFS: Proof[] = [
  {
    id: 'proof-001',
    progress_id: 'prog-001',
    progress: MOCK_PROGRESSES[0],
    user_id: 'usr-001',
    user: MOCK_PROFILES[0],
    type: 'github',
    title: 'GitHub Repository VERA Mobile & Control Center',
    description: 'Repository resmi implementasi sistem Progress, Milestone, Proof & Timeline.',
    external_url: 'https://github.com/rezkyaditya21/VERA',
    visibility: 'public',
    verification_status: 'unverified',
    created_at: '2026-09-06T14:30:00Z',
    updated_at: '2026-09-06T14:30:00Z',
  },
  {
    id: 'proof-002',
    progress_id: 'prog-001',
    progress: MOCK_PROGRESSES[0],
    user_id: 'usr-001',
    user: MOCK_PROFILES[0],
    type: 'website',
    title: 'Live VERA Control Center Dashboard',
    description: 'Dashboard admin operasional terhubung dengan PostgreSQL Supabase.',
    external_url: 'http://localhost:3000',
    visibility: 'public',
    verification_status: 'unverified',
    created_at: '2026-09-07T09:15:00Z',
    updated_at: '2026-09-07T09:15:00Z',
  },
  {
    id: 'proof-003',
    progress_id: 'prog-002',
    progress: MOCK_PROGRESSES[1],
    user_id: 'usr-002',
    user: MOCK_PROFILES[1],
    type: 'certificate',
    title: 'Sertifikat UI/UX Design Specialist',
    description: 'Diterbitkan oleh Interaction Design Foundation setelah menyelesaikan 8 modul design system.',
    external_url: 'https://verify.interaction-design.org/cert/12345',
    media_url: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    visibility: 'public',
    verification_status: 'verified',
    verified_at: '2026-08-31T11:00:00Z',
    verified_by: 'usr-admin-01',
    created_at: '2026-08-30T17:00:00Z',
    updated_at: '2026-08-31T11:00:00Z',
  },
  {
    id: 'proof-004',
    progress_id: 'prog-003',
    progress: MOCK_PROGRESSES[2],
    user_id: 'usr-003',
    user: MOCK_PROFILES[2],
    type: 'other',
    title: 'Tautan Channel VIP Telegram Crypto',
    description: 'Link menuju bot investasi yang mencurigakan.',
    external_url: 'https://t.me/cryptopromobot_scam',
    visibility: 'public',
    verification_status: 'unverified',
    created_at: '2026-09-05T04:10:00Z',
    updated_at: '2026-09-05T04:10:00Z',
  },
];

